name: QuizStream Code Quality Assurance

on:
  push:
    branches:
      - '**'

jobs:
  # Lint check job
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 18.18.0
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-18.18.0-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-18.18.0-

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  # TypeScript type checking job
  typescript:
    name: TypeScript Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 18.18.0
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-18.18.0-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-18.18.0-

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript Check
        run: npm run typescript:check

  # Prettier formatting check job
  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 18.18.0
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-18.18.0-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-18.18.0-

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier Check
        run: npm run prettier:check
